#pragma once

#include <IcelinSdk.PvZGW2/PrimitiveTypes.h>

namespace fb
{

/* TypeInfo (Array): 0000000142853180
   RuntimeId:        163C
   TypeInfo Kind:    EnumTypeInfo
   Address:          00000001430C8288
*/
enum ShaderConstantFunction
{
  ShaderConstantFunction_ViewMatrix = 0,
  ShaderConstantFunction_NormalBasisTransforms = 90,
  ShaderConstantFunction_NormalBasisCubemapTexture = 89,
  ShaderConstantFunction_NormalBasisGBufferTexture = 88,
  ShaderConstantFunction_SceneTexture = 87,
  ShaderConstantFunction_BestFitNormalScaleTexture = 86,
  ShaderConstantFunction_LightShaftTexture = 85,
  ShaderConstantFunction_HorizonScatteringTexture = 84,
  ShaderConstantFunction_HeightFogColorAdd = 83,
  ShaderConstantFunction_HeightFogColorMulMinTransmittance = 82,
  ShaderConstantFunction_MiePolarizationFilter = 81,
  ShaderConstantFunction_RayleighPolarizationFilter = 80,
  ShaderConstantFunction_RayleighScatteringCoefficient = 79,
  ShaderConstantFunction_Light1Dir = 78,
  ShaderConstantFunction_Light0Dir = 77,
  ShaderConstantFunction_MieGMaxDistanceTransTexDepthMieCoef = 76,
  ShaderConstantFunction_FogSkyGradientUVRanges = 75,
  ShaderConstantFunction_FogEnabledModeSkyModeUseLight2 = 74,
  ShaderConstantFunction_FogMiscParam = 73,
  ShaderConstantFunction_FogHeightFogCoefficients = 72,
  ShaderConstantFunction_FogStartDistance = 71,
  ShaderConstantFunction_FogColor = 70,
  ShaderConstantFunction_FogColorCoefficients = 69,
  ShaderConstantFunction_FogCoefficients = 68,
  ShaderConstantFunction_FogForwardScatteringSunDir = 67,
  ShaderConstantFunction_FogForwardScatteringColorPresence = 66,
  ShaderConstantFunction_FogForwardScatteringParamsLuminanceScaleFogEnable = 65,
  ShaderConstantFunction_FogParams = 64,
  ShaderConstantFunction_DxVectorBufferOffsets = 91,
  ShaderConstantFunction_TransparentCurve = 63,
  ShaderConstantFunction_DistortionMaxValue = 92,
  ShaderConstantFunction_ObjectWorldPosition = 94,
  ShaderConstantFunction_ForwardShadingLocalPRDataArray = 121,
  ShaderConstantFunction_ForwardShadingLocalPRDepthTextureArray = 120,
  ShaderConstantFunction_ForwardShadingLocalPRTextureArray = 119,
  ShaderConstantFunction_ForwardShadingLightIndexBuffer = 118,
  ShaderConstantFunction_ForwardShadingLightGridBuffer = 117,
  ShaderConstantFunction_ForwardShadingLightConstants = 116,
  ShaderConstantFunction_ForwardShadingIESTextureArray = 115,
  ShaderConstantFunction_ForwardShadingAreaShadowLightCount = 114,
  ShaderConstantFunction_ForwardShadingAreaShadowLightDataArray = 113,
  ShaderConstantFunction_ForwardShadingAreaLightCount = 112,
  ShaderConstantFunction_ForwardShadingAreaLightDataArray = 111,
  ShaderConstantFunction_ForwardShadingPunctualShadowLightCount = 110,
  ShaderConstantFunction_ForwardShadingPunctualShadowLightDataArray = 109,
  ShaderConstantFunction_ForwardShadingPunctualLightCount = 108,
  ShaderConstantFunction_ForwardShadingPunctualLightDataArray = 107,
  ShaderConstantFunction_ForwardShadingLocalIBLCount = 106,
  ShaderConstantFunction_ForwardShadingLocalIBLDataArray = 105,
  ShaderConstantFunction_ForwardShadingLocalIBLTextureArray = 104,
  ShaderConstantFunction_ForwardShadingIBLConstant = 103,
  ShaderConstantFunction_ForwardShadingPreIntegratedFG = 102,
  ShaderConstantFunction_ForwardShadingPreIntegratedDL = 101,
  ShaderConstantFunction_PrevUserData0 = 100,
  ShaderConstantFunction_UserData1 = 99,
  ShaderConstantFunction_UserData0 = 98,
  ShaderConstantFunction_TessellationCameraPos = 97,
  ShaderConstantFunction_TessellationCrViewProjMatrix = 96,
  ShaderConstantFunction_TessellationScreenSize = 95,
  ShaderConstantFunction_ObjectScale = 93,
  ShaderConstantFunction_TransparentStartAndSlopeAndClamp = 62,
  ShaderConstantFunction_SpotLightsConeAngles = 61,
  ShaderConstantFunction_SpotLightsDirection = 60,
  ShaderConstantFunction_OutdoorLightDir = 27,
  ShaderConstantFunction_ScreenSize = 26,
  ShaderConstantFunction_Time = 25,
  ShaderConstantFunction_ProjectionKxKyKzKw = 24,
  ShaderConstantFunction_DepthBufferTexture = 23,
  ShaderConstantFunction_LightMapSkyVisibilityTexture = 22,
  ShaderConstantFunction_LightMapDirectionTextureB = 21,
  ShaderConstantFunction_LightMapDirectionTextureG = 20,
  ShaderConstantFunction_LightMapDirectionTexture = 19,
  ShaderConstantFunction_LightMapIrradianceTexture = 18,
  ShaderConstantFunction_LightMapUvTranslation = 17,
  ShaderConstantFunction_LightMapUvTransform = 16,
  ShaderConstantFunction_LightProbeShL2 = 15,
  ShaderConstantFunction_PrevBoneVectors = 14,
  ShaderConstantFunction_BoneVectors = 13,
  ShaderConstantFunction_PrevWorldMatrix = 12,
  ShaderConstantFunction_WorldMatrix = 11,
  ShaderConstantFunction_PrevWorldViewProjMatrix = 10,
  ShaderConstantFunction_PrevViewProjMatrix = 9,
  ShaderConstantFunction_ExposureMultipliers = 8,
  ShaderConstantFunction_ViewSettings = 7,
  ShaderConstantFunction_CameraPos = 6,
  ShaderConstantFunction_CrWorldViewProjMatrix = 5,
  ShaderConstantFunction_CrViewProjMatrix = 4,
  ShaderConstantFunction_WorldViewProjMatrix = 3,
  ShaderConstantFunction_WorldViewMatrix = 2,
  ShaderConstantFunction_ViewProjMatrix = 1,
  ShaderConstantFunction_OutdoorLightAngularRadius = 28,
  ShaderConstantFunction_OutdoorLightHemisphereDir = 29,
  ShaderConstantFunction_OutdoorLightKeyLuminance = 30,
  ShaderConstantFunction_OutdoorLightIlluminanceAndSpecularScale = 31,
  ShaderConstantFunction_SpotLightsColorAndAttenuation = 59,
  ShaderConstantFunction_SpotLightsPositionAndRadius = 58,
  ShaderConstantFunction_SpotLightCount = 57,
  ShaderConstantFunction_PointLightsColorAndAttenuation = 56,
  ShaderConstantFunction_PointLightsPositionAndRadius = 55,
  ShaderConstantFunction_PointLightCount = 54,
  ShaderConstantFunction_OutdoorLightCloudShadowTexture = 53,
  ShaderConstantFunction_OutdoorLightCloudShadowOffsetScaleExponentAndFade = 52,
  ShaderConstantFunction_OutdoorLightCloudShadowEnable = 51,
  ShaderConstantFunction_OutdoorLightCustomEnvmapScaleAmbientAndSkyVisExponent = 50,
  ShaderConstantFunction_OutdoorLightSkyEnvmap8BitTexInvScale = 49,
  ShaderConstantFunction_OutdoorLightEnvmapsMipmapCount = 48,
  ShaderConstantFunction_OutdoorLightKeyIlluminanceEnvmap = 47,
  ShaderConstantFunction_ForwardShadingLocalPRCount = 122,
  ShaderConstantFunction_OutdoorLightBottomColorEnvmap = 46,
  ShaderConstantFunction_OutdoorLightDynamicEnvmap = 44,
  ShaderConstantFunction_OutdoorLightCustomEnvmap = 43,
  ShaderConstantFunction_OutdoorLightSkyEnvmap = 42,
  ShaderConstantFunction_OutdoorLightTransparencyShadowmapTexture = 41,
  ShaderConstantFunction_OutdoorLightShadowmapTextureArray = 40,
  ShaderConstantFunction_OutdoorLightShadowmapTexture = 39,
  ShaderConstantFunction_OutdoorLightShadowmapSizeAndInvSize = 38,
  ShaderConstantFunction_OutdoorLightShadowTransformArraySize = 37,
  ShaderConstantFunction_OutdoorLightShadowTransformArray = 36,
  ShaderConstantFunction_OutdoorLightShadowTransform = 35,
  ShaderConstantFunction_OutdoorLightBottomColor = 34,
  ShaderConstantFunction_OutdoorLightTopColor = 33,
  ShaderConstantFunction_OutdoorLightKeySpecularColorAndHemisphereVisibility = 32,
  ShaderConstantFunction_OutdoorLightTopColorEnvmap = 45,
  ShaderConstantFunctionCount = 123,
};

}
