#pragma once

#include <IcelinSdk.PvZGW2/PrimitiveTypes.h>

namespace fb
{

/* TypeInfo (Array): 0000000142854EA0
   RuntimeId:        17E2
   TypeInfo Kind:    EnumTypeInfo
   Address:          00000001430B52C0
*/
enum UIInputAction
{
  UIInputAction_NavigateUp = 0,
  UIInputAction_SpectatorViewPlayer9 = 57,
  UIInputAction_SpectatorViewPlayer8 = 56,
  UIInputAction_SpectatorViewPlayer7 = 55,
  UIInputAction_SpectatorViewPlayer6 = 54,
  UIInputAction_SpectatorViewPlayer5 = 53,
  UIInputAction_SpectatorViewPlayer4 = 52,
  UIInputAction_SpectatorViewPlayer3 = 51,
  UIInputAction_SpectatorViewPlayer10 = 58,
  UIInputAction_SpectatorViewPlayer2 = 50,
  UIInputAction_SpectatorViewFreeCam = 48,
  UIInputAction_SpectatorViewThirdPerson = 47,
  UIInputAction_SpectatorViewFirstPerson = 46,
  UIInputAction_SpectatorViewTableTop = 45,
  UIInputAction_SpectatorTargetNext = 44,
  UIInputAction_SpectatorTargetPrev = 43,
  UIInputAction_SpectatorViewNext = 42,
  UIInputAction_SpectatorViewPlayer1 = 49,
  UIInputAction_SpectatorViewPlayer11 = 59,
  UIInputAction_SpectatorViewPlayer12 = 60,
  UIInputAction_SpectatorViewPlayer13 = 61,
  UIInputAction_SelectAll = 78,
  UIInputAction_Minimize = 77,
  UIInputAction_Start = 76,
  UIInputAction_SpectatorSquadActivate = 75,
  UIInputAction_SpectatorSquadDown = 74,
  UIInputAction_SpectatorSquadUp = 73,
  UIInputAction_SpectatorSquadRight = 72,
  UIInputAction_SpectatorSquadLeft = 71,
  UIInputAction_SpectatorTargetNextOnTeam = 70,
  UIInputAction_SpectatorTargetPrevOnTeam = 69,
  UIInputAction_SpectatorTargetNextInSquad = 68,
  UIInputAction_SpectatorTargetPrevInSquad = 67,
  UIInputAction_SpectatorHudVisibility = 66,
  UIInputAction_SpectatorViewOptions = 65,
  UIInputAction_SpectatorViewPlayer16 = 64,
  UIInputAction_SpectatorViewPlayer15 = 63,
  UIInputAction_SpectatorViewPlayer14 = 62,
  UIInputAction_SpectatorViewPrev = 41,
  UIInputAction_Size = 79,
  UIInputAction_MultipleSelect = 40,
  UIInputAction_BattledashToggle = 38,
  UIInputAction_MapZoom = 16,
  UIInputAction_RThumb = 15,
  UIInputAction_LThumb = 14,
  UIInputAction_View = 13,
  UIInputAction_Edit = 12,
  UIInputAction_Tab = 11,
  UIInputAction_Back = 10,
  UIInputAction_MapSize = 17,
  UIInputAction_OK = 9,
  UIInputAction_Menu = 7,
  UIInputAction_Deactivate = 6,
  UIInputAction_TabRight = 5,
  UIInputAction_TabLeft = 4,
  UIInputAction_NavigateRight = 3,
  UIInputAction_NavigateLeft = 2,
  UIInputAction_NavigateDown = 1,
  UIInputAction_Cancel = 8,
  UIInputAction_SayAllChat = 18,
  UIInputAction_TeamChat = 19,
  UIInputAction_SquadChat = 20,
  UIInputAction_ConversationChangeSelection = 37,
  UIInputAction_ConversationSkip = 36,
  UIInputAction_ConversationSelect = 35,
  UIInputAction_TacticalMenu = 34,
  UIInputAction_MenuTriggerRight = 33,
  UIInputAction_MenuTriggerLeft = 32,
  UIInputAction_NavigateRRight = 31,
  UIInputAction_NavigateRLeft = 30,
  UIInputAction_NavigateRDown = 29,
  UIInputAction_NavigateRUp = 28,
  UIInputAction_DigitalRight = 27,
  UIInputAction_DigitalLeft = 26,
  UIInputAction_DigitalDown = 25,
  UIInputAction_DigitalUp = 24,
  UIInputAction_ToggleMinimapType = 23,
  UIInputAction_ToggleChat = 22,
  UIInputAction_CommoRose = 21,
  UIInputAction_VoipPushToTalk = 39,
  UIInputAction_None = 80,
};

}
