#pragma once

#include <IcelinSdk.PvZGW2/PrimitiveTypes.h>
#include <IcelinSdk.PvZGW2/GameShared/BlueprintBundleReference.h>

namespace fb
{

/* TypeInfo (Array): 000000014284D780
   RuntimeId:        113B
   TypeInfo Kind:    ValueTypeInfo
   VfTable:          0000000000000000
   Address:          00000001430C90E8
   Default Value:    000000014284D798
*/
#pragma pack(push, 8)
struct AutoGeneratedBundle
{
  typedef struct ValueTypeInfo TypeInfo_t;

  BlueprintBundleReference BlueprintBundleReference; /* 0x0000 */

private:
  /* Intended for use in Ida. Do not remove. */
  static void IdaForceImport(TypeInfo_t);
}; /* Size: 0x0038 */
#pragma pack(pop)

static_assert(sizeof(AutoGeneratedBundle) == 56);

}
